#pragma once

// Important! Character names may be subject of copyright
enum CharacterType : char {
	/* 0 */    CHARACTER_TYPE_SOL,
	/* 1 */    CHARACTER_TYPE_KY,
	/* 2 */    CHARACTER_TYPE_MAY,
	/* 3 */    CHARACTER_TYPE_MILLIA,
	/* 4 */    CHARACTER_TYPE_ZATO,
	/* 5 */    CHARACTER_TYPE_POTEMKIN,
	/* 6 */    CHARACTER_TYPE_CHIPP,
	/* 7 */    CHARACTER_TYPE_FAUST,
	/* 8 */    CHARACTER_TYPE_AXL,
	/* 9 */    CHARACTER_TYPE_VENOM,
	/* 10 */   CHARACTER_TYPE_SLAYER,
	/* 11 */   CHARACTER_TYPE_INO,
	/* 12 */   CHARACTER_TYPE_BEDMAN,
	/* 13 */   CHARACTER_TYPE_RAMLETHAL,
	/* 14 */   CHARACTER_TYPE_SIN,
	/* 15 */   CHARACTER_TYPE_ELPHELT,
	/* 16 */   CHARACTER_TYPE_LEO,
	/* 17 */   CHARACTER_TYPE_JOHNNY,
	/* 18 */   CHARACTER_TYPE_JACKO,
	/* 19 */   CHARACTER_TYPE_JAM,
	/* 20 */   CHARACTER_TYPE_HAEHYUN,
	/* 21 */   CHARACTER_TYPE_RAVEN,
	/* 22 */   CHARACTER_TYPE_DIZZY,
	/* 23 */   CHARACTER_TYPE_BAIKEN,
	/* 24 */   CHARACTER_TYPE_ANSWER
};
