#pragma once
#include <d3d9.h>

namespace {
	const D3DCOLOR COLOR_PUSHBOX = D3DCOLOR_ARGB(0, 255, 255, 0);
	const int THICKNESS_PUSHBOX = 1;

	const D3DCOLOR COLOR_HITBOX = D3DCOLOR_ARGB(0, 255, 0, 0);
	const int THICKNESS_HITBOX = 3000;
	const int DISPLAY_DURATION_HITBOX_THAT_HIT = 5; // set to 0 to turn feature off

	const D3DCOLOR COLOR_HURTBOX = D3DCOLOR_ARGB(0, 0, 255, 0);
	const int THICKNESS_HURTBOX = 3000;
	const D3DCOLOR COLOR_HURTBOX_COUNTERHIT = D3DCOLOR_ARGB(0, 0, 255, 255);
	const int THICKNESS_HURTBOX_COUNTERHIT = 3000;

	const D3DCOLOR COLOR_HURTBOX_OLD = D3DCOLOR_ARGB(0, 128, 128, 128);
	const int DISPLAY_DURATION_HURTBOX_THAT_GOT_HIT = 10;  // set to 0 to turn feature off

	const D3DCOLOR COLOR_THROW = D3DCOLOR_ARGB(0, 0, 0, 255);
	const int THICKNESS_THROW = 3000;
	const D3DCOLOR COLOR_THROW_PUSHBOX = D3DCOLOR_ARGB(0, 0, 0, 255);
	const int THICKNESS_THROW_PUSHBOX = 3000;
	const D3DCOLOR COLOR_THROW_XYORIGIN = D3DCOLOR_ARGB(0, 128, 0, 255);
	const int THICKNESS_THROW_XYORIGIN = 3000;
	const int DISPLAY_DURATION_THROW = 5;

	const D3DCOLOR COLOR_REJECTION = D3DCOLOR_ARGB(0, 0, 0, 255);
	const int THICKNESS_REJECTION = 3000;
	const int DISPLAY_DURATION_REJECTION = 5;

	const int THICKNESS_WAY_TOO_NUMEROUS_SUMMONS = 1;  // set to 0 to turn feature off

	D3DCOLOR replaceAlpha(DWORD alpha, D3DCOLOR color) {
		return (alpha << 24) | (color & 0xFFFFFF);
	}
}